### ISSUE TITLE
CMakeLists.txt is missing from the repository

### ISSUE THREAD

**Issue by Linuxmaker** [greenbone/gsa#3257]
**Expected behavior**
This command should be feasible 
`~/gvm-source/gsa/build$ cmake .. -DCMAKE_INSTALL_PREFIX=/opt/gvm`

**Actual behavior**
Instead, execution stops with 
`CMake Error: The source directory "/opt/gvm/gvm-source/gsa" does not appear to contain CMakeLists.txt.`

**Steps to reproduce**
The "CMakeLists.txt" file does not exist in all the other required modules such as openvas etc., just not in the current Git repository for GSA. 

I would argue that CMakeLists.txt has been forgotten. 

### GVM versions

**gsa:** (gsad --version)
-bash: gsad: command not found. 
**gvm:** (gvmd --version)
Greenbone Vulnerability Manager 21.10.0~dev1~git-f85346061-main
GIT revision f85346061-main
Manager DB revision 249
**openvas-scanner:** (openvassd --version)
openvas --version
OpenVAS 21.10.0~dev1~git-624a6280-main
GIT revision ~git-624a6280-main
gvm-libs 21.10.0~dev1~git-99effe84-main

**gvm-libs:**

### Environment

**Operating system:**
Linux openvas 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

**Installation method / source:** (packages, source installation)
Source installation with Git

**Comment by Linuxmaker** [comment]
If you want to get the repository via Git, this file is missing. However, it does exist in the tar file.

**Comment by cfi-gb** [comment]
`gsa` has been split from `gsad` and doesn't use a `CMakeLists.txt` at all (because it isn't a C based project anymore). This has been announced / can be seen here:

https://community.greenbone.net/t/github-infrastructure-changes/10462#split-of-gsa-and-gsad-3

The updated build instructions are also available here:

https://github.com/greenbone/gsa/tree/stable#installation
