### ISSUE TITLE
[BUILD][ARCH-LINUX (AUR)] [need to update dependencies]   [throw e;]  [Package subpath './lib/tokenize' is not defined by "exports"]

### ISSUE THREAD

**Issue by freedom1b2830** [greenbone/gsa#3422]
Linux archlinux 5.17.3-arch1-1 #1 SMP PREEMPT Thu, 14 Apr 2022 01:18:36 +0000 x86_64 GNU/Linux

packeges:
```cmake 3.23.1-1
gnutls 3.7.4-1
gvmd 21.4.3-1
lib32-gnutls 3.7.4-1
lib32-libxml2 2.9.13-2
libxml2 2.9.13-2
nmap 7.92-1
node-gyp 9.0.0-1
nodejs 17.9.0-2
nodejs-nopt 5.0.0-2
npm 8.5.5-1
openvas-scanner 21.4.2-1
ospd 21.4.3-1
ospd-openvas 21.4.2-1
python-redis 4.0.1-1
redis 6.2.6-2
```

install wiki:
https://wiki.archlinux.org/title/OpenVAS
step: install ```gsa```

### GVM versions

**gsa:** (gsad --version)

**gvm:** (gvmd --version)
```
Greenbone Vulnerability Manager 21.4.3
Manager DB revision 242
Copyright (C) 2009-2021 Greenbone Networks GmbH
License: AGPL-3.0-or-later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
openvas --version
```
OpenVAS 21.4.2
```

**openvas-scanner:** (openvassd --version)

**gvm-libs:**
```
gvm-libs 21.4.2
```
**Installation method / source:** (packages, source installation)
AUR:https://aur.archlinux.org/packages/gsa
### Logfiles
[gsa_install.txt](https://github.com/greenbone/gsa/files/8524159/gsa_install.txt)

**Comment by freedom1b2830** [comment]
There is a solution, is to update the dependencies
comment https://aur.archlinux.org/packages/gsa#comment-844976 by jpoppe helped me

**Comment by Dexus** [comment]
The reference system is Debian Buster. All other builds are not official supported. If the package is from your community please open a bug ticket there.

**Comment by freedom1b2830** [comment]
The problem is the ```PostCSS``` dependency which is used by the ```styled-components``` for ```node.js 17```
doing ```yarn upgrade``` in ```gsa``` directory before building ```solves this problem```,
```Solving the problem is up to you.```

**Comment by Dexus** [comment]
@freedom1b2830
Maybe you don't understand that the packages used are fixed with their version in packages.json/yarn.lock. If your system is different from the reference system, the problem is not with us. Alternatively you can download the source and the corresponding node_modules as zip. With this in mind, on Debian Buster it works as expected. If you have problems on your ARCH OS it's up to you, to fix the problem. At least you should use the latest version and nothing that is already behind by 2 patches.

`yarn install` will produce a reliable setup, to make sure that yarn.lock file will not updated while running the command, you can add also `--frozen-lockfile`.

Best Regards, Josef

**Comment by freedom1b2830** [comment]
I understand you, debian uses node 10
and in archlinux node17
(now I will create a ticket about using the '''yarn upgrade''' update before building)
end.

**Comment by Dexus** [comment]
We won't do that, because that way we can never be sure that our web interface will work as expected. With every build you will get a different result. If you have QA, this is a disaster.
