### ISSUE TITLE
[ 7.0.2] Linking against libmicrohttpd 0.9.59 will result in warnings during start up

### ISSUE THREAD

**Issue by tuxmaster** [greenbone/gsa#374]
When using the last version of libmicrohttpd, the following warning will shown on start up:

> gsad: Warning: MHD_USE_THREAD_PER_CONNECTION must be used only with MHD_USE_INTERNAL_POLLING_THREAD. Flag MHD_USE_INTERNAL_POLLING_THREAD was added. Consider setting MHD_USE_INTERNAL_POLLING_THREAD explicitly.

**Comment by cfi-gb** [comment]
Fixed in master with https://github.com/greenbone/gsa/pull/327

**Comment by bjoernricks** [comment]
Won't fix for openvas 9.

**Comment by bjoernricks** [comment]
Won't fix means a PR to backport #327 for openvas 9/gsa 7 is still welcome. But I am not going to write the patches myself.

**Comment by PLeontios** [comment]
Well, I get the same message:
Warning:
MHD_USE_THREAD_PER_CONNECTION must be used only with MHD_USE_INTERNAL_POLLING_THREAD.
Flag MHD_USE_INTERNAL_POLLING_THREAD was added.
Consider setting MHD_USE_INTERNAL_POLLING_THREAD explicitly.

after a run OpenVAS-start and while all services seem to start OK (green).

Also, when scanning is running I get occasionally an internal error related to internal communication with scan manager and have to press on "assume sane state" in order to return to the normal screen.

Anyone?

Thank you in advance,
Panos

**Comment by cfi-gb** [comment]
> You should take a look at the logs of openvasmd and openvassd instead.

and report a new issue (if you can find any errors related to this) in the respective issue tracker of the component (openvasmd: https://github.com/greenbone/gvmd/issues, openvassd: https://github.com/greenbone/openvas-scanner/issues)
