### ISSUE TITLE
gsad vulnerable sweet32

### ISSUE THREAD

**Issue by petern3t** [greenbone/gsa#845]
### Steps to reproduce
1.
2.
3.

### GVM versions
**gsa:** (gsad --version)

**gvm:** (gvmd --version)

**openvas-scanner:** (openvassd --version)

**gvm-libs:**

**openvas-smb:**

### Environment
**Operating system:**

**Installation method / source:** (packages, source installation)

### Logfiles

```

```

**Comment by cfi-gb** [comment]
@petern3t Please note the following in the shown template:

> 3. be aware that this is not a support forum. If your issue is more a question than a bug report, please check http://openvas.org/ for available support options.

and close this issue here.

Rationale: This is not a bug but a configuration issue within your GnuTLS setup. You can either configure a global GnuTLS priorities string (see your favorite search engine) so all applications using GnuTLS are using a secure SSL/TLS setup or you can use a specific one for GSA with the ``--gnutls-priorities=<string>`` parameter of the ``gsad`` daemon.
